security:
    encoders:
        legacy_bcrypt:
            algorithm: bcrypt
            
        App\Entity\User:
            algorithm: auto
            migrate_from: 
                - legacy_bcrypt

    role_hierarchy:
        ROLE_API:         ROLE_API
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_API, ROLE_USER, ROLE_ADMIN]

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        amreu_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: amreu_user_provider

            guard:
                authenticators:
                    - amreu.login.form.authenticator
                entry_point: amreu.login.form.authenticator
                
            form_login:
                login_path: user_security_login_check
                check_path: user_security_login_check
                
            logout:
                path: user_security_logout

    access_control:
        - { path: ^/[a-z]+/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_ADMIN }