# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    erase_credentials: false
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        AppBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_API:         ROLE_API
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_API, ROLE_USER, ROLE_ADMIN]

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            fr3d_ldap_httpbasic: ~
            fr3d_ldap:  ~
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            anonymous: true
            logout:
                path: fos_user_security_logout
            remember_me:
                secret: '%secret%'
                lifetime: 604800 # 1 week in seconds

    access_control:
        - { path: ^/[a-z]+/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_ADMIN }